URL uniformisation for namespaces prefix (/@ vs /&40) (#601)
flora-pm/flora-server pull request #765
Opened 2024-10-12 14:59 UTC by fel-mazo

Hello,

I made the changes described in the ticket.
Let me know if there is something I can improve.

attached, screenshots of what changed

![image](https://github.com/user-attachments/assets/c3dd5e1b-33a4-4092-82ab-450c4a16b2d0)
![image](https://github.com/user-attachments/assets/e79ac790-5817-43b6-b39b-d947ad8ba09c)
![image](https://github.com/user-attachments/assets/b98278c3-17f8-455d-a61d-8b1e3b500c35)
![image](https://github.com/user-attachments/assets/4bf48bb1-6583-4140-85df-939145053a17)

2024-10-13 14:51 UTC, tchoutri commented
@fel-mazo Thank you very much! I think the `mkURL` function may also cause problems: https://github.com/flora-pm/flora-server/blob/development/src/web/FloraWeb/Components/PaginationNav.hs#L44-L54

2024-10-14 13:53 UTC, fel-mazo commented
yes defo ! will look into it asap

2024-10-20 13:58 UTC, fel-mazo commented
I just updated my branch, I also tried to reorganize my changes a bit and put everything in the Links module, let me know if the names are fine as they are or if it would be better to change them.

2024-10-20 17:05 UTC, tchoutri requested changes

2024-10-20 17:05 UTC, tchoutri commented on src/web/FloraWeb/Pages/Templates/Packages.hs
> +import Text.PrettyPrint qualified as PP
Let's keep third-party import statements in the upper paragraph. :)

2024-11-08 20:44 UTC, merged